repos:
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.58.7
    hooks:
      - id: swiftformat
        args: [--config, .swiftformat]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-ast
        stages: [post-commit]
      - id: check-executables-have-shebangs
        stages: [post-commit]
      - id: check-toml
        stages: [post-commit]
      - id: check-vcs-permalinks
        stages: [post-commit]
      - id: check-xml
        stages: [post-commit]
      - id: check-yaml
        stages: [post-commit]
      - id: detect-private-key
        stages: [post-commit]
      - id: forbid-submodules
        stages: [post-commit]
